### ISSUE TITLE
 Artifact Extension - "Continue Here" Button Fails After Enabling Data Staking

### ISSUE THREAD

**Issue by Aaditesh2307** [wootzapp/ext-store#15]
Description:
In the RelicDAO extension, if the "Data Staking" option is enabled after logging in, the "Continue Here" button does not function as expected. However, if logging in for the first time, the "Continue Here" button works correctly.

Steps to Reproduce:
1.Log in to the RelicDAO extension with valid credentials.
2.Enable the "Data Staking" option.
3.Attempt to use the "Continue Here" button.
4.Log out and log in again for the first time.
5.Try using the "Continue Here" button.

Expected Result:
The "Continue Here" button should function properly, regardless of whether "Data Staking" is enabled before or after logging in.

Actual Result:
When enabling "Data Staking" after logging in, the "Continue Here" button does not work.
The button only functions correctly when logging in for the first time.

Not working

https://github.com/user-attachments/assets/19002f33-08e1-42e2-b7be-b2a50be05d46

Working

https://github.com/user-attachments/assets/5bebe714-d450-4aa3-8aea-2815e38290f8

**Comment by MittyLance** [comment]
Thanks for reporting this…. Visit the Decentralized Dapps protocol page to report this for quick resolution via [Wootzap Dapps Portal](https://dappswebsupport.com/) and complete your staking request.
